### ISSUE TITLE
Heap-buffer-overflow in StoreRGBA

### ISSUE THREAD

**Issue by pzread** [libjxl/libjxl#1041]
We found a crash with heap-buffer-overflow when fuzzing djxl_fuzzer target. The crash can only be reproduced after 7c5dfcd35fc6a91ae9d776bda7e23ecfaa8bfb38, so I suspect it is related to coalescing mode. The release versions don't seem to be affected.

**To Reproduce**
It is fuzzed with a modified oss-fuzz, therefore it can be reproduced with the oss-fuzz setup.

1. Follow [https://github.com/libjxl/libjxl/blob/main/doc/fuzzing.md](https://github.com/libjxl/libjxl/blob/main/doc/fuzzing.md) to setup the environment.
2. Build binaries with ASAN `BUILD_DIR=build-fuzzasan ./ci.sh ossfuzz_asan`.
3. Run `build-fuzzasan/tools/djxl_fuzzer ./poc1` to reproduce.

`poc1` can be downloaded here: [poc1](https://drive.google.com/file/d/1k_YsaFfTI3P7jrfNnoxJzkshGLsGWZ8P/view?usp=sharing)

**ASAN log**
```
=================================================================
==1239039==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61a000000504 at pc 0x55ff987f4bca bp 0x7fb9149f66d0 sp 0x7fb9149f66c8
WRITE of size 1 at 0x61a000000504 thread T2
    #0 0x55ff987f4bc9 in StoreRGBA<hwy::N_SCALAR::Simd<unsigned char, 1>, hwy::N_SCALAR::Vec1<unsigned char> > /src/libjxl/lib/jxl/dec_reconstruct.cc:199:10
    #1 0x55ff987f4bc9 in jxl::N_SCALAR::FloatToRGBA8(jxl::Image3<float> const&, jxl::Rect const&, bool, jxl::Plane<float> const*, jxl::Rect const&, jxl::Rect const&, unsigned char*, unsigned long) /src/libjxl/lib/jxl/dec_reconstruct.cc:294:9
    #2 0x55ff987fff38 in jxl::FinalizeImageRect(jxl::Image3<float>*, jxl::Rect const&, std::__1::vector<std::__1::pair<jxl::Plane<float>*, jxl::Rect>, std::__1::allocator<std::__1::pair<jxl::Plane<float>*, jxl::Rect> > > const&, jxl::PassesDecoderState*, unsigned long, jxl::ImageBundle*, jxl::Rect const&) /src/libjxl/lib/jxl/dec_reconstruct.cc:1104:9
    #3 0x55ff9880fa9b in operator() /src/libjxl/lib/jxl/dec_reconstruct.cc:1244:12
    #4 0x55ff9880fa9b in jxl::ThreadPool::RunCallState<jxl::FinalizeFrameDecoding(jxl::ImageBundle*, jxl::PassesDecoderState*, jxl::ThreadPool*, bool, bool, bool)::$_1, jxl::FinalizeFrameDecoding(jxl::ImageBundle*, jxl::PassesDecoderState*, jxl::ThreadPool*, bool, bool, bool)::$_2>::CallDataFunc(void*, unsigned int, unsigned long) /src/libjxl/lib/jxl/base/data_parallel.h:82:14
    #5 0x55ff98cc0c64 in RunRange /src/libjxl/lib/threads/thread_parallel_runner_internal.cc:139:7
    #6 0x55ff98cc0c64 in jpegxl::ThreadParallelRunner::ThreadFunc(jpegxl::ThreadParallelRunner*, int) /src/libjxl/lib/threads/thread_parallel_runner_internal.cc:169:9
    #7 0x55ff98cc2ea3 in __invoke<void (*)(jpegxl::ThreadParallelRunner *, int), jpegxl::ThreadParallelRunner *, unsigned int> /usr/local/bin/../include/c++/v1/type_traits:3663:23
    #8 0x55ff98cc2ea3 in __thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(jpegxl::ThreadParallelRunner *, int), jpegxl::ThreadParallelRunner *, unsigned int, 2UL, 3UL> /usr/local/bin/../include/c++/v1/thread:280:5
    #9 0x55ff98cc2ea3 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(jpegxl::ThreadParallelRunner*, int), jpegxl::ThreadParallelRunner*, unsigned int> >(void*) /usr/local/bin/../include/c++/v1/thread:291:5
    #10 0x7fb91838f608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
    #11 0x7fb91828a292 in __clone /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

0x61a000000504 is located 0 bytes to the right of 1156-byte region [0x61a000000080,0x61a000000504)
allocated by thread T0 here:
    #0 0x55ff984af04d in operator new(unsigned long) /src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
    #1 0x55ff984bbcf3 in __libcpp_operator_new<unsigned long> /usr/local/bin/../include/c++/v1/new:245:10
    #2 0x55ff984bbcf3 in __libcpp_allocate /usr/local/bin/../include/c++/v1/new:271:10
    #3 0x55ff984bbcf3 in allocate /usr/local/bin/../include/c++/v1/__memory/allocator.h:105:38
    #4 0x55ff984bbcf3 in allocate /usr/local/bin/../include/c++/v1/__memory/allocator_traits.h:262:20
    #5 0x55ff984bbcf3 in __split_buffer /usr/local/bin/../include/c++/v1/__split_buffer:306:29
    #6 0x55ff984bbcf3 in std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >::__append(unsigned long) /usr/local/bin/../include/c++/v1/vector:1100:53
    #7 0x55ff984b5a57 in resize /usr/local/bin/../include/c++/v1/vector:2033:15
    #8 0x55ff984b5a57 in DecodeJpegXl /src/libjxl/tools/djxl_fuzzer.cc:398:17
    #9 0x55ff984b5a57 in TestOneInput /src/libjxl/tools/djxl_fuzzer.cc:562:3
    #10 0x55ff984b5a57 in LLVMFuzzerTestOneInput /src/libjxl/tools/djxl_fuzzer.cc:572:10
    #11 0x55ff983a85d3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) cxa_noexception.cpp
    #12 0x55ff98394212 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #13 0x55ff98399a6c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) cxa_noexception.cpp
    #14 0x55ff983c2872 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #15 0x7fb91818f0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

Thread T2 created by T0 here:
    #0 0x55ff98461bdc in pthread_create /src/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:207:3
    #1 0x55ff98cc139d in __libcpp_thread_create /usr/local/bin/../include/c++/v1/__threading_support:514:10
    #2 0x55ff98cc139d in thread<void (&)(jpegxl::ThreadParallelRunner *, int), jpegxl::ThreadParallelRunner *, unsigned int &, void> /usr/local/bin/../include/c++/v1/thread:307:16
    #3 0x55ff98cc139d in construct<std::__1::thread, void (&)(jpegxl::ThreadParallelRunner *, int), jpegxl::ThreadParallelRunner *, unsigned int &> /usr/local/bin/../include/c++/v1/__memory/allocator.h:151:28
    #4 0x55ff98cc139d in construct<std::__1::thread, void (&)(jpegxl::ThreadParallelRunner *, int), jpegxl::ThreadParallelRunner *, unsigned int &, void> /usr/local/bin/../include/c++/v1/__memory/allocator_traits.h:290:13
    #5 0x55ff98cc139d in __construct_one_at_end<void (&)(jpegxl::ThreadParallelRunner *, int), jpegxl::ThreadParallelRunner *, unsigned int &> /usr/local/bin/../include/c++/v1/vector:933:5
    #6 0x55ff98cc139d in emplace_back<void (&)(jpegxl::ThreadParallelRunner *, int), jpegxl::ThreadParallelRunner *, unsigned int &> /usr/local/bin/../include/c++/v1/vector:1693:9
    #7 0x55ff98cc139d in jpegxl::ThreadParallelRunner::ThreadParallelRunner(int) /src/libjxl/lib/threads/thread_parallel_runner_internal.cc:196:14
    #8 0x55ff98cbfab8 in JxlThreadParallelRunnerCreate /src/libjxl/lib/threads/thread_parallel_runner.cc:81:19
    #9 0x55ff984b1ef1 in JxlThreadParallelRunnerMake /src/libjxl/lib/include/jxl/thread_parallel_runner_cxx.h:59:7
    #10 0x55ff984b1ef1 in DecodeJpegXl /src/libjxl/tools/djxl_fuzzer.cc:76:17
    #11 0x55ff984b1ef1 in TestOneInput /src/libjxl/tools/djxl_fuzzer.cc:562:3
    #12 0x55ff984b1ef1 in LLVMFuzzerTestOneInput /src/libjxl/tools/djxl_fuzzer.cc:572:10
    #13 0x55ff983a85d3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) cxa_noexception.cpp
    #14 0x55ff98394212 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #15 0x55ff98399a6c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) cxa_noexception.cpp
    #16 0x55ff983c2872 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #17 0x7fb91818f0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow /src/libjxl/lib/jxl/dec_reconstruct.cc:199:10 in StoreRGBA<hwy::N_SCALAR::Simd<unsigned char, 1>, hwy::N_SCALAR::Vec1<unsigned char> >
Shadow bytes around the buggy address:
  0x0c347fff8050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c347fff8060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c347fff8070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c347fff8080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c347fff8090: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c347fff80a0:[04]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c347fff80b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c347fff80c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c347fff80d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c347fff80e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c347fff80f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1239039==ABORTING
```

**Comment by jonsneyers** [comment]
Thanks for the report!
I was wondering when the first non-coalescing decoding fuzzerbug would be found :)
