### ISSUE TITLE
Issue 45866: kimageformats:kimgio_jxl_fuzzer: Integer-overflow in jxl::palette_internal::GetPaletteValue

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#1260]
This issue was found by [oss-fuzz](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45866), which is testing Qt plug-in for JXL format. libjxl 0.6.1 is used.

Test file:
[oss-fuzz_45866.zip](https://github.com/libjxl/libjxl/files/8318714/oss-fuzz_45866.zip)

Please verify whether the issue is serious or not and/or whether it was resolved meanwhile.

```
/src/libjxl/lib/jxl/modular/transform/palette.h:87:14: runtime error: signed integer overflow: 128 * 16777216 cannot be represented in type 'int'
	 #0 0x5d222a in jxl::palette_internal::GetPaletteValue(int const*, int, unsigned long, int, int, int) libjxl/lib/jxl/modular/transform/palette.h:87:14
	 #1 0x5d47ca in operator() libjxl/lib/jxl/modular/transform/palette.h:264:21
	 #2 0x5d47ca in jxl::ThreadPool::RunCallState<jxl::Status (unsigned long), jxl::InvPalette(jxl::Image&, unsigned int, unsigned int, unsigned int, jxl::Predictor, jxl::weighted::Header const&, jxl::ThreadPool*)::$_5>::CallDataFunc(void*, unsigned int, unsigned long) libjxl/lib/jxl/base/data_parallel.h:88:14
	 #3 0x4fd308 in jxl::ThreadPool::SequentialRunnerStatic(void*, void*, int (*)(void*, unsigned long), void (*)(void*, unsigned int, unsigned long), unsigned int, unsigned int) libjxl/lib/jxl/base/data_parallel.cc:18:5
	 #4 0x5d44ae in Run<jxl::Status (unsigned long), (lambda at /src/libjxl/lib/jxl/modular/transform/palette.h:255:11)> libjxl/lib/jxl/base/data_parallel.h:51:12
	 #5 0x5d44ae in bool jxl::ThreadPool::Run<jxl::InvPalette(jxl::Image&, unsigned int, unsigned int, unsigned int, jxl::Predictor, jxl::weighted::Header const&, jxl::ThreadPool*)::$_5>(unsigned int, unsigned int, jxl::ThreadPool::SkipInit, jxl::InvPalette(jxl::Image&, unsigned int, unsigned int, unsigned int, jxl::Predictor, jxl::weighted::Header const&, jxl::ThreadPool*)::$_5 const&, char const*) libjxl/lib/jxl/base/data_parallel.h:60:12
	 #6 0x5cfec5 in RunOnPool<jxl::ThreadPool::SkipInit, (lambda at /src/libjxl/lib/jxl/modular/transform/palette.h:255:11)> libjxl/lib/jxl/base/data_parallel.h:0:9
	 #7 0x5cfec5 in jxl::InvPalette(jxl::Image&, unsigned int, unsigned int, unsigned int, jxl::Predictor, jxl::weighted::Header const&, jxl::ThreadPool*) libjxl/lib/jxl/modular/transform/palette.h:253:7
	 #8 0x5cf6e9 in jxl::Transform::Inverse(jxl::Image&, jxl::weighted::Header const&, jxl::ThreadPool*) libjxl/lib/jxl/modular/transform/transform.cc:32:14
	 #9 0x5cc473 in jxl::Image::undo_transforms(jxl::weighted::Header const&, int, jxl::ThreadPool*) libjxl/lib/jxl/modular/modular_image.cc:20:23
	 #10 0x71cd93 in jxl::ModularFrameDecoder::FinalizeDecoding(jxl::PassesDecoderState*, jxl::ThreadPool*, jxl::ImageBundle*) libjxl/lib/jxl/dec_modular.cc:605:6
	 #11 0x6ea6b2 in jxl::FrameDecoder::Flush() libjxl/lib/jxl/dec_frame.cc:830:3
	 #12 0x6e187b in jxl::FrameDecoder::FinalizeFrame() libjxl/lib/jxl/dec_frame.cc:927:3
	 #13 0x515eee in jxl::(anonymous namespace)::JxlDecoderProcessInternal(JxlDecoderStruct*, unsigned char const*, unsigned long) libjxl/lib/jxl/decode.cc:1340:28
	 #14 0x5119ef in JxlDecoderProcessInput libjxl/lib/jxl/decode.cc:1755:14
```

**Comment by jonsneyers** [comment]
I think https://github.com/libjxl/libjxl/pull/1155 should resolve this.
