### ISSUE TITLE
Possible integer overflow in DecodeModularChannelMAANS

### ISSUE THREAD

**Issue by lovell** [libjxl/libjxl#140]
Sorry to be the bearer of bad news but the libvips fuzzers appear to have something against libjxl today :(

This image causes an integer overflow when decoding using the latest code on the `main` branch.

[clusterfuzz-testcase-minimized-6288583458684928.txt](https://github.com/libjxl/libjxl/files/6626055/clusterfuzz-testcase-minimized-6288583458684928.txt)

```
/src/libjxl/lib/jxl/modular/encoding/encoding.cc:228:24: runtime error: signed integer overflow: 1107427842 + 1073742852 cannot be represented in type 'int'
#0 0x10eedda in jxl::DecodeModularChannelMAANS(jxl::BitReader*, jxl::ANSSymbolReader*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, std::__1::vector<jxl::PropertyDecisionNode, std::__1::allocator<jxl::PropertyDecisionNode> > const&, jxl::weighted::Header const&, int, unsigned long, jxl::Image*) libjxl/lib/jxl/modular/encoding/encoding.cc:228:24
#1 0x10f179c in jxl::ModularDecode(jxl::BitReader*, jxl::Image&, jxl::GroupHeader&, unsigned long, jxl::ModularOptions*, std::__1::vector<jxl::PropertyDecisionNode, std::__1::allocator<jxl::PropertyDecisionNode> > const*, jxl::ANSCode const*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const*, bool) libjxl/lib/jxl/modular/encoding/encoding.cc:487:5
#2 0x10f1cc8 in jxl::ModularGenericDecompress(jxl::BitReader*, jxl::Image&, jxl::GroupHeader*, unsigned long, jxl::ModularOptions*, int, std::__1::vector<jxl::PropertyDecisionNode, std::__1::allocator<jxl::PropertyDecisionNode> > const*, jxl::ANSCode const*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const*, bool) libjxl/lib/jxl/modular/encoding/encoding.cc:517:21
#3 0x1456f7b in jxl::ModularFrameDecoder::DecodeGlobalInfo(jxl::BitReader*, jxl::FrameHeader const&, bool) libjxl/lib/jxl/dec_modular.cc:211:23
#4 0x13a4938 in jxl::FrameDecoder::ProcessDCGlobal(jxl::BitReader*) libjxl/lib/jxl/dec_frame.cc:381:46
#5 0x13a1191 in jxl::FrameDecoder::ProcessSections(jxl::FrameDecoder::SectionInfo const*, unsigned long, 
```

Perhaps further clamping might be required here:

https://github.com/libjxl/libjxl/blob/87ebbe9d5cd7581afbcce650e6879bccf80e3beb/lib/jxl/modular/encoding/encoding.cc#L225-L228

**Comment by lovell** [comment]
Thank you for the quick fix!
