### ISSUE TITLE
JxlEncoderProcessOutput returned JXL_ENC_ERR_GENERIC when encoding fp32 inputs

### ISSUE THREAD

**Issue by zhou13** [libjxl/libjxl#2363]
**Describe the bug**
JxlEncoderProcessOutput returned JXL_ENC_ERROR when encoding fp32 inputs

**To Reproduce**

To reproduce the error, install `imagecodecs` with `pip install imagecodecs` and run the following python program:
```python
import numpy as np
from imagecodecs import imwrite

buffer = np.load("1.npy")
print(buffer.shape, buffer.dtype)
imwrite("1.jxl", buffer)
```
Here is the example buffer:
[1.npy.zip](https://github.com/cgohlke/imagecodecs/files/11162460/1.npy.zip)

The example is produced in python because I don't know how to give `cjxl` an fp32 buffer.

I got error
```
(1536, 1536) float32
Traceback (most recent call last):
  File "reproduce.py", line 6, in <module>
    imwrite("1.jxl", buffer)
  File "/miniconda/envs/main/lib/python3.8/site-packages/imagecodecs/imagecodecs.py", line 1399, in imwrite
    image: bytes = codec(data, **kwargs)
  File "imagecodecs\_jpegxl.pyx", line 561, in imagecodecs._jpegxl.jpegxl_encode
imagecodecs._jpegxl.JpegxlError: JxlEncoderProcessOutput returned JXL_ENC_ERROR
```

In my bug report to the python library: https://github.com/cgohlke/imagecodecs/issues/71, the library author says that `JxlEncoderGetError` just returns `JXL_ENC_ERR_GENERIC` in this case.

**Expected behavior**

**Screenshots**
If applicable, add screenshots or example input/output images to help explain your problem.

**Environment**
 - OS: Linux
 - Compiler version: Unknown
 - CPU type: x86_64
 - cjxl/djxl version string: 0.8.1

**Comment by mo271** [comment]
see also #2444
