### ISSUE TITLE
OSS Fuzz Issue 64982: graphicsmagick:coder_JXL_fuzzer: Ill in jxl::Abort

### ISSUE THREAD

**Issue by bobfriesenhahn** [libjxl/libjxl#3024]
**Describe the bug**

This issue (an assertion/abort) has emerged due to GraphicsMagick now including libjxl in its oss-fuzz testing. The problem appears to only occur (so far) in i386 builds and it appears to be a weakness in the cache-aligned memory allocator.

The stack trace looks like this:

```
            #0 0x823d4b2 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
            #1 0xab55bb5 in jxl::Abort() libjxl/lib/jxl/base/status.h:137:3
            #2 0xabdf350 in jxl::CacheAligned::Allocate(unsigned int, unsigned int) libjxl/lib/jxl/cache_aligned.cc:64:3
            #3 0xac58bb0 in Allocate libjxl/lib/jxl/cache_aligned.h:43:12
            #4 0xac58bb0 in AllocateArray libjxl/lib/jxl/cache_aligned.h:61:29
            #5 0xac58bb0 in jxl::PlaneBase::PlaneBase(unsigned int, unsigned int, unsigned int) libjxl/lib/jxl/image.cc:90:14
            #6 0xb4a9b6f in Plane libjxl/lib/jxl/image.h:153:9
            #7 0xb4a9b6f in jxl::AcStrategyImage::AcStrategyImage(unsigned int, unsigned int) libjxl/lib/jxl/ac_strategy.cc:90:7
            #8 0xb1aca17 in jxl::InitializePassesSharedState(jxl::FrameHeader const&, jxl::PassesSharedState*, bool) libjxl/lib/jxl/passes>
            #9 0xb069ad7 in jxl::FrameDecoder::InitFrameOutput() libjxl/lib/jxl/dec_frame.cc:200:3
            #10 0xabf6beb in JxlDecoderProcessCodestream libjxl/lib/jxl/decode.cc:1269:9
            #11 0xabf6beb in HandleBoxes(JxlDecoderStruct*) libjxl/lib/jxl/decode.cc:1899:33
            #12 0xabee412 in JxlDecoderProcessInput libjxl/lib/jxl/decode.cc:2050:29
            #13 0x85f02c0 in ReadJXLImage /src/graphicsmagick/coders/jxl.c:977:16
            #14 0x836e080 in ReadImage /src/graphicsmagick/magick/constitute.c:1682:13
            #15 0x8317e57 in BlobToImage /src/graphicsmagick/magick/blob.c:786:13
            #16 0x82836b7 in Magick::Image::read(Magick::Blob const&) /src/graphicsmagick/Magick++/lib/Image.cpp:1592:5
            #17 0x82776cb in LLVMFuzzerTestOneInput /src/graphicsmagick/fuzzing/coder_fuzzer.cc:22:15
            #18 0x8137ffe in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned int) /src/llvm-project/compiler-rt/lib/fuzzer/>
            #19 0x8122f5e in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned int) /src/llvm-project/compiler-rt/lib/fuzzer/Fuzze>
            #20 0x8128b60 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned int)) /src/llvm-project/compiler-r>
            #21 0x8152747 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
            #22 0xf7bfbed4 in __libc_start_main
            #23 0x811a0a5 in _start
```

**To Reproduce**

A compressed tarball containing all of the details from the oss-fuzz report is attached.

**Expected behavior**

Do not crash.

**Environment**
 - OS: Ubuntu 20.04 LTS
 - Compiler version: 15.0.0
 - CPU type: i386
 - cjxl/djxl version string: cjxl v0.10.0 961307e [SSE4,SSE2]

**Additional context**

[oss-fuzz-64982.tar.gz](https://github.com/libjxl/libjxl/files/13666445/oss-fuzz-64982.tar.gz)

**Comment by eustas** [comment]
This one is easy: internal check detects that too large piece of memory is about to be allocated.
I believe API frontend checks that decoded image is not too large... but it does not account for 32-bit systems. Will fix soon.

**Comment by eustas** [comment]
Well, since embedder does not pass compiler definition `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` it is not so easy to limit image size. Still we have plans to propagate allocation error to API level (instead of aborting).

**Comment by eustas** [comment]
Exactly, reacting to memory manager answer is what I meant by "plans".
A quick and dirty fix for fuzzer is to add `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` compilation defenition when compiling for oss-fuzz and do not set memory manager to decoder.

I'm going to work on proper fix after dealing in CMS dependency.
