### ISSUE TITLE
After Update to extra/libjxl 0.10.1-1 calibre won't work (extra/calibre 7.6.0-1)

### ISSUE THREAD

**Issue by wasundwarum** [libjxl/libjxl#3370]
After Update to extra/libjxl 0.10.1-1 calibre will not work correctly. A Downgrade to libjxl-0.9.2-1
all works fine

**Comment by mo271** [comment]
Likely related to the libjxl-gdk-pixbuf issue: #3358

**Comment by wasundwarum** [comment]
Hello,

Error Message is:

Failed to import PyQt module: PyQt6.QtWebEngineCore with error: libjxl.so.0.9: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/usr/bin/calibre-parallel", line 21, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/calibre/calibre/utils/ipc/worker.py", line 215, in main
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/gui_launch.py", line 102, in wrapper
    return func(*a, **kw)
           ^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/gui_launch.py", line 117, in ebook_viewer
    from calibre.gui2.viewer.main import main
  File "/usr/lib/calibre/calibre/gui2/viewer/main.py", line 15, in <module>
    from calibre.gui2.viewer.ui import EbookViewer, is_float
  File "/usr/lib/calibre/calibre/gui2/viewer/ui.py", line 29, in <module>
    from calibre.gui2.viewer.annotations import (
  File "/usr/lib/calibre/calibre/gui2/viewer/annotations.py", line 13, in <module>
    from calibre.gui2.viewer.web_view import viewer_config_dir
  File "/usr/lib/calibre/calibre/gui2/viewer/web_view.py", line 12, in <module>
    from qt.webengine import (
ImportError: cannot import name 'QWebEnginePage' from 'qt.webengine' (/usr/lib/calibre/qt/webengine.py)

**Comment by mo271** [comment]
This seems to be different from the gdk-pixbuf issue, but rather some linking problem
