### ISSUE TITLE
Potential null pointer dereference in FinalizeImageRect - ASan

### ISSUE THREAD

**Issue by oxygen005** [libjxl/libjxl#842]
**Describe the bug**
This 49 byte input file (found by fuzzing) [crash-min.jxl.txt](https://github.com/libjxl/libjxl/files/7520009/crash-min.jxl.txt) causes a segmentation fault when trying to decode with djxl.

**To Reproduce**
`djxl crash-min.jxl.txt --allow_partial_files --allow_more_progressive_steps`
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==8608==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f3a0f4cb3c8 bp 0x7f3a0967e7b0 sp 0x7f3a0967df38 T7)
==8608==The signal is caused by a READ memory access.
==8608==Hint: address points to the zero page.
    #0 0x7f3a0f4cb3c7  (/lib/x86_64-linux-gnu/libc.so.6+0xbb3c7)
    #1 0x4ddf5d in __asan_memcpy (/home/ubuntu/libjxl/build/tools/djxl+0x4ddf5d)
    #2 0x65c4e0 in jxl::FinalizeImageRect(jxl::Image3<float>*, jxl::Rect const&, std::vector<std::pair<jxl::Plane<float>*, jxl::Rect>, std::allocator<std::pair<jxl::Plane<float>*, jxl::Rect> > > const&, jxl::PassesDecoderState*, unsigned long, jxl::ImageBundle*, jxl::Rect const&) /home/ubuntu/libjxl/lib/jxl/dec_reconstruct.cc:1018:11
    #3 0x6693fd in jxl::FinalizeFrameDecoding(jxl::ImageBundle*, jxl::PassesDecoderState*, jxl::ThreadPool*, bool, bool, bool)::$_2::operator()(unsigned long, unsigned long) const /home/ubuntu/libjxl/lib/jxl/dec_reconstruct.cc:1190:12
    #4 0x6693fd in jxl::ThreadPool::RunCallState<jxl::FinalizeFrameDecoding(jxl::ImageBundle*, jxl::PassesDecoderState*, jxl::ThreadPool*, bool, bool, bool)::$_1, jxl::FinalizeFrameDecoding(jxl::ImageBundle*, jxl::PassesDecoderState*, jxl::ThreadPool*, bool, bool, bool)::$_2>::CallDataFunc(void*, unsigned int, unsigned long) /home/ubuntu/libjxl/lib/jxl/base/data_parallel.h:88
    #5 0x9505a3 in jpegxl::ThreadParallelRunner::RunRange(jpegxl::ThreadParallelRunner*, unsigned long, int) /home/ubuntu/libjxl/lib/threads/thread_parallel_runner_internal.cc:139:7
    #6 0x9505a3 in jpegxl::ThreadParallelRunner::ThreadFunc(jpegxl::ThreadParallelRunner*, int) /home/ubuntu/libjxl/lib/threads/thread_parallel_runner_internal.cc:169
    #7 0x7f3a102ad6de  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbd6de)
    #8 0x4ed11e in __asan::AsanThread::ThreadStart(unsigned long, __sanitizer::atomic_uintptr_t*) (/home/ubuntu/libjxl/build/tools/djxl+0x4ed11e)
    #9 0x7f3a105876da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)
    #10 0x7f3a0f53171e in clone (/lib/x86_64-linux-gnu/libc.so.6+0x12171e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0xbb3c7) 
Thread T7 created by T0 here:
    #0 0x4386c0 in pthread_create (/home/ubuntu/libjxl/build/tools/djxl+0x4386c0)
    #1 0x7f3a102ad994 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbd994)
    #2 0x51e125 in jxl::ThreadPoolInternal::ThreadPoolInternal(int) /home/ubuntu/libjxl/lib/jxl/base/thread_pool_internal.h:33:9
    #3 0x51e125 in jpegxl::tools::(anonymous namespace)::DecompressMain(int, char const**) /home/ubuntu/libjxl/tools/djxl_main.cc:91
    #4 0x51e125 in main /home/ubuntu/libjxl/tools/djxl_main.cc:197
    #5 0x7f3a0f431bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)

==8608==ABORTING
```

**Expected behavior**
The decoder should produce an error message without segmentation fault.

**Environment**
- OS: Ubuntu 18.04 (Windows Subsystem for Linux)
- Compiler version: clang 6.0
- CPU type: x86_64
- cjxl/djxl version string: JPEG XL decoder v0.7.0 6692183  asan [Scalar]

**Additional context**
The file was found using fuzzing (AFL++) and the `--allow_partial_files --allow_more_progressive_steps` flags.

**Comment by eustas** [comment]
Thanks for the report. Will look into this soon.
